### ISSUE TITLE
Different results in tmp and eval with same sentences

### ISSUE THREAD

**Issue by WiraDKP** [ttaoREtw/Tacotron-pytorch#2]
Hi tao,
Thank you for your effort to code the Tacotron. I would like to ask why do we get different results in tmp/results and eval/results even if we use the same sentences for eval ?
The train results in tmp sounds very good, but in eval, it sounds like it doesn't work. Shouldn't it be the same if we use same sentences ?
Thanks in advance

**Comment by ttaoREtw** [comment]
Although the issue is closed, I reply it because there may be some other people have this question, too.
This is because, in the training phase, we use "teacher forcing" to decode mel-spectrograms, and in the testing phase, we use "greedy strategy" to decode. 
These different decoding ways cause the performance gap. 😃
